# Generated by Django 3.2.7 on 2021-09-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0002_classdetail_classes_classsubject_localguardian_mediumtype_parents_section_sessions_students_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='grades',
        ),
    ]
