# Generated by Django 3.2.7 on 2021-09-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0004_section_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='classes',
        ),
    ]
