# Generated by Django 3.2.7 on 2021-09-26 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0008_studentregistration_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockzenmaster.branch'),
        ),
        migrations.AddField(
            model_name='section',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockzenmaster.classes'),
        ),
    ]
