# Generated by Django 3.2.7 on 2021-09-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0012_studentattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='isPresent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
