# Generated by Django 3.2.7 on 2021-09-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0013_alter_studentattendance_ispresent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='studentregistration',
        ),
    ]
