# Generated by Django 3.2.7 on 2021-09-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0014_remove_studentattendance_studentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='attendance',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Grade', max_length=100, null=True),
        ),
    ]
