# Generated by Django 3.2.7 on 2021-09-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0015_studentregistration_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='attendance',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=100, null=True),
        ),
    ]
