# Generated by Django 3.2.7 on 2021-10-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0020_auto_20211019_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=200, null=True)),
                ('month', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
