# Generated by Django 3.2.7 on 2021-10-24 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0021_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='startDate',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockzenmaster.session'),
        ),
    ]
