# Generated by Django 3.2.7 on 2021-11-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0022_auto_20211024_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='isPresent',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=200, null=True),
        ),
    ]
