# Generated by Django 3.2.7 on 2021-11-15 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0023_alter_studentattendance_ispresent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidtermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct1', models.CharField(blank=True, max_length=200, null=True)),
                ('ct2', models.CharField(blank=True, max_length=200, null=True)),
                ('ct3', models.CharField(blank=True, max_length=200, null=True)),
                ('ct4', models.CharField(blank=True, max_length=200, null=True)),
                ('term', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockzenmaster.subject')),
            ],
        ),
        migrations.CreateModel(
            name='FinaltermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct1', models.CharField(blank=True, max_length=200, null=True)),
                ('ct2', models.CharField(blank=True, max_length=200, null=True)),
                ('ct3', models.CharField(blank=True, max_length=200, null=True)),
                ('ct4', models.CharField(blank=True, max_length=200, null=True)),
                ('term', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockzenmaster.subject')),
            ],
        ),
    ]
