# Generated by Django 3.2.7 on 2021-11-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0024_finaltermresult_midtermresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltermresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockzenmaster.students'),
        ),
        migrations.AddField(
            model_name='midtermresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockzenmaster.students'),
        ),
    ]
