# Generated by Django 3.2.7 on 2021-11-18 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0025_auto_20211115_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='finaltermresult',
            old_name='ct1',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='midtermresult',
            old_name='ct1',
            new_name='mark',
        ),
        migrations.RemoveField(
            model_name='finaltermresult',
            name='ct2',
        ),
        migrations.RemoveField(
            model_name='finaltermresult',
            name='ct3',
        ),
        migrations.RemoveField(
            model_name='finaltermresult',
            name='ct4',
        ),
        migrations.RemoveField(
            model_name='finaltermresult',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='finaltermresult',
            name='term',
        ),
        migrations.RemoveField(
            model_name='finaltermresult',
            name='total',
        ),
        migrations.RemoveField(
            model_name='midtermresult',
            name='ct2',
        ),
        migrations.RemoveField(
            model_name='midtermresult',
            name='ct3',
        ),
        migrations.RemoveField(
            model_name='midtermresult',
            name='ct4',
        ),
        migrations.RemoveField(
            model_name='midtermresult',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='midtermresult',
            name='term',
        ),
        migrations.RemoveField(
            model_name='midtermresult',
            name='total',
        ),
        migrations.AddField(
            model_name='finaltermresult',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockzenmaster.exams'),
        ),
        migrations.AddField(
            model_name='midtermresult',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockzenmaster.exams'),
        ),
    ]
