# Generated by Django 3.2.7 on 2021-12-14 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0026_auto_20211118_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockzenmaster.subject'),
        ),
        migrations.AlterField(
            model_name='finaltermresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockzenmaster.studentregistration'),
        ),
        migrations.AlterField(
            model_name='midtermresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockzenmaster.studentregistration'),
        ),
    ]
