# Generated by Django 3.2.7 on 2021-12-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockzenmaster', '0027_auto_20211214_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='subject',
            field=models.ManyToManyField(to='blockzenmaster.Subject'),
        ),
    ]
